import fs from "node:fs";
import path from "node:path";
import hre from "hardhat";

/**
 * Deploy the UserVault implementation + VaultFactory.
 *
 * Required env vars:
 *   DEPLOYER_PRIVATE_KEY        — set in hardhat config networks
 *   FACTORY_PROTOCOL_FEE_RECEIVER — address for protocol fees (can be deployer)
 *   FACTORY_DEFAULT_FEE_BPS     — default fee bps for new vaults (0 for V1)
 *   FACTORY_MAX_VAULTS_PER_USER — max vaults per user (default: 3)
 *   UNISWAP_ROUTER_ADDRESS      — swap router address for reference
 *
 * Usage:
 *   npx hardhat run scripts/deploy-factory.ts --network baseSepolia
 */

function sleep(ms: number) {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

function requireAddress(value: string, label: string) {
	try {
		// Ethers v6: validate and checksum
		return hre.ethers.getAddress(value);
	} catch {
		throw new Error(`${label} must be a valid EVM address (got: "${value}")`);
	}
}

async function getDeployConfig() {
	const [deployer] = await hre.ethers.getSigners();
	const feeReceiverRaw =
		process.env.FACTORY_PROTOCOL_FEE_RECEIVER ?? deployer.address;
	const feeReceiver = requireAddress(
		feeReceiverRaw,
		"FACTORY_PROTOCOL_FEE_RECEIVER"
	);
	const defaultFeeBps = Number(process.env.FACTORY_DEFAULT_FEE_BPS ?? "0");
	const maxVaultsPerUser = Number(
		process.env.FACTORY_MAX_VAULTS_PER_USER ?? "3"
	);

	console.log("Deploying UserVault + VaultFactory...");
	console.log("  Network:", hre.network.name);
	console.log("  Deployer:", deployer.address);
	console.log("  Fee receiver:", feeReceiver);
	console.log("  Default fee bps:", defaultFeeBps);
	console.log("  Max vaults/user:", maxVaultsPerUser);

	return { deployer, feeReceiver, defaultFeeBps, maxVaultsPerUser };
}

async function deployContracts(config: {
	deployer: { address: string };
	feeReceiver: string;
	defaultFeeBps: number;
	maxVaultsPerUser: number;
}) {
	// 1. Deploy UserVault implementation
	console.log("\n1. Deploying UserVault implementation...");
	const UserVault = await hre.ethers.getContractFactory("UserVault");
	const implementation = await UserVault.deploy();
	await implementation.waitForDeployment();
	const implAddress = await implementation.getAddress();
	console.log("   ✓ UserVault implementation:", implAddress);

	await sleep(5000);

	// 2. Deploy VaultFactory
	console.log("\n2. Deploying VaultFactory...");
	const VaultFactory = await hre.ethers.getContractFactory("VaultFactory");
	const factory = await VaultFactory.deploy(
		implAddress,
		config.deployer.address,
		config.feeReceiver,
		config.defaultFeeBps,
		config.maxVaultsPerUser
	);
	await factory.waitForDeployment();
	const factoryAddress = await factory.getAddress();
	console.log("   ✓ VaultFactory:", factoryAddress);

	return { implAddress, factoryAddress };
}

async function verifyContracts(
	implAddress: string,
	factoryAddress: string,
	config: {
		deployer: { address: string };
		feeReceiver: string;
		defaultFeeBps: number;
		maxVaultsPerUser: number;
	}
) {
	const isLocal =
		hre.network.name === "hardhat" || hre.network.name === "localhost";

	if (isLocal || !process.env.ETHERSCAN_API_KEY) {
		return;
	}

	console.log("\n3. Verifying contracts...");

	const verify = async (address: string, args: unknown[]) => {
		try {
			await hre.run("verify:verify", {
				address,
				constructorArguments: args,
			});
			console.log(`   ✓ ${address} verified`);
		} catch (error: unknown) {
			const message = error instanceof Error ? error.message : String(error);
			if (message.includes("Already Verified")) {
				console.log(`   ✓ ${address} already verified`);
			} else {
				console.error(`   ✗ ${address} verification failed:`, message);
			}
		}
	};

	await verify(implAddress, []);
	await sleep(3000);
	await verify(factoryAddress, [
		implAddress,
		config.deployer.address,
		config.feeReceiver,
		config.defaultFeeBps,
		config.maxVaultsPerUser,
	]);
}

async function generateDefinitions(
	implAddress: string,
	factoryAddress: string
) {
	console.log("\n4. Generating definitions...");
	const userVaultArtifact = await hre.artifacts.readArtifact("UserVault");
	const factoryArtifact = await hre.artifacts.readArtifact("VaultFactory");

	let networkKey: string;
	if (hre.network.name === "baseSepolia" || hre.network.name === "sepolia") {
		networkKey = "testnet";
	} else if (hre.network.name === "base" || hre.network.name === "mainnet") {
		networkKey = "mainnet";
	} else {
		networkKey = "localhost";
	}

	const definitionsPath = path.join(process.cwd(), "factory-definitions.ts");
	const content = `// Auto-generated by deploy-factory script
// Generated on: ${new Date().toISOString()}
// Network: ${hre.network.name}

export const USER_VAULT_ABI = ${JSON.stringify(userVaultArtifact.abi, null, 2)} as const;

export const VAULT_FACTORY_ABI = ${JSON.stringify(factoryArtifact.abi, null, 2)} as const;

export const ${networkKey} = {
	implementation: "${implAddress}" as const,
	factory: "${factoryAddress}" as const,
};

// Convenience exports for current network
export const USER_VAULT_IMPLEMENTATION_ADDRESS = "${implAddress}" as const;
export const VAULT_FACTORY_ADDRESS = "${factoryAddress}" as const;
`;

	fs.writeFileSync(definitionsPath, content);
	console.log("   ✓ Definitions written to:", definitionsPath);
}

async function main() {
	const config = await getDeployConfig();
	const { implAddress, factoryAddress } = await deployContracts(config);

	await sleep(5000);
	await verifyContracts(implAddress, factoryAddress, config);
	await generateDefinitions(implAddress, factoryAddress);

	console.log("\n✓ Deployment complete!");
	console.log("  Implementation:", implAddress);
	console.log("  Factory:", factoryAddress);
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
